default:
  image: node:22.21.1
  tags:
    - profiq
#  # cache is disabled due to slowdown it causes in this small pipeline
#  # but on bigger projects, it can be beneficial to enable. The way to enable
#  # it can be found in the comments
#  cache: &default_cache
#    key:
#      files:
#        - 'package-lock.json'
#        - '**/package.json'
#    paths:
#      - .npm
#    policy: pull

stages:
  - code_quality
  - test
  - build

variables:
  GIT_DEPTH: 1
  IMAGE_NAME: europe-central2-docker.pkg.dev/pq-reference-app-dev/pq-reference-app-be-dev/backend-dev

.set_npm_config:
  before_script:
    - npm config set cache .npm
    - npm config set prefer-offline true

.rule_mr_and_main:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

.npm_ci_only_root:
  before_script:
    - !reference [.set_npm_config, before_script]
    - npm ci --workspaces=false

.npm_ci_frontend:
  before_script:
    - !reference [.set_npm_config, before_script]
    - npm ci -w frontend --include-workspace-root

.npm_ci_backend:
  before_script:
    - !reference [.set_npm_config, before_script]
    - npm ci -w backend --include-workspace-root

## this updates the cache
#warmup_cache:
#  stage: .pre
#  cache:
#    # this is a YAML anchor.
#    # docs: https://docs.gitlab.com/ci/yaml/yaml_optimization/#anchors
#    <<: *default_cache
#    policy: pull-push
#  extends:
#    - .rule_mr_and_main
#  script:
#    - npm ci --cache .npm --prefer-offline

code_quality:
  stage: code_quality
  extends:
    - .rule_mr_and_main
    - .npm_ci_only_root
  script:
    - npm run lint:eslint
    - npm run lint:prettier

frontend-test:
  stage: test
  extends:
    - .rule_mr_and_main
    - .npm_ci_frontend
  script:
    # if unit tests fail, there is no reason to waste time installing playwright
    # so run it first
    - npm run test:unit -w frontend
    - npm run init:playwright -w frontend
    - npm run test:component -w frontend

backend-unit:
  stage: test
  extends:
    - .rule_mr_and_main
    - .npm_ci_backend
  script:
    - npm run test -w backend

backend-e2e:
  stage: test
  extends:
    - .rule_mr_and_main
    - .npm_ci_backend
  script:
    - npm run test:e2e-emulator -w backend

backend-build:
  image:
    name: moby/buildkit:rootless
    entrypoint: ['']
  stage: build
  tags:
    - profiq
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
      variables:
        IMAGE_TAG: ${CI_MERGE_REQUEST_ID}
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        IMAGE_TAG: ${CI_COMMIT_SHA}
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    # due to permission issues with Docker in Docker (DinD), we use buildkit (https://docs.gitlab.com/ci/docker/using_buildkit/)
    # which does not support docker login and docker build commands, so we have to use direct echo of the credentials
    - mkdir -p ~/.docker
    - |
      echo "{
        \"auths\": {
          \"europe-central2-docker.pkg.dev\": {
            \"auth\": \"$(printf "%s:%s" "_json_key_base64" "${GOOGLE_APPLICATION_CREDENTIALS_BASE64}" | base64 -w0)\"
          }
        }
      }" > ~/.docker/config.json

  script:
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --opt platform=linux/amd64 \
        --local context=. \
        --local dockerfile=backend/ \
        --output type=image,\"name=${IMAGE_NAME}:${IMAGE_TAG},${IMAGE_NAME}:latest\",push=true
