default:
  image: node:22.21.1

stages:
  - code_quality
  - test

.rule_mr_and_main:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

.npm_ci_only_root:
  before_script:
    - npm ci --workspaces=false

.npm_ci_frontend:
  before_script:
    - npm ci -w frontend --include-workspace-root

.npm_ci_backend:
  before_script:
    - npm ci -w backend --include-workspace-root

code_quality:
  stage: code_quality
  extends:
    - .rule_mr_and_main
    - .npm_ci_only_root
  script:
    - npm run lint:eslint
    - npm run lint:prettier

frontend-test:
  stage: test
  extends:
    - .rule_mr_and_main
    - .npm_ci_frontend
  script:
    - !reference [.npm_ci_frontend, before_script]
    # if unit tests fail, there is no reason to waste time installing playwright
    # so run it first
    - npm run test:unit -w frontend
    - npm run init:playwright -w frontend
    - npm run test:component -w frontend

backend-unit:
  stage: test
  extends:
    - .rule_mr_and_main
    - .npm_ci_backend
  script:
    - npm run test -w backend

backend-e2e:
  stage: test
  extends:
    - .rule_mr_and_main
    - .npm_ci_backend
  script:
    - npm run test:e2e -w backend
